version: "3.8"
services:
  client:
    container_name: blog-frontend
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./:/app
